sudo: required
dist: trusty
language: cpp

matrix:
    include:
        - env: GCC_VERSION=5
          os: linux
          compiler: gcc-5
          addons: &gcc5
            apt:
              packages:
                - g++-5
              sources:
                - ubuntu-toolchain-r-test

install:
    - if [ -n "$GCC_VERSION" ]; then export CXX="g++-${GCC_VERSION}" CC="gcc-${GCC_VERSION}"; fi
    - if [ -n "$GCC_VERSION" ]; then export CXXFLAGS="${CXXFLAGS} -std=gnu++14"; fi

script:
    - cd ./sayan_test 
    - make -f makefile.gcc debug && ./bin/Debug/sayan_test
    - make -f makefile.gcc release && ./bin/Release/sayan_test
