
WORKDIR = `pwd`

LD = $(CXX)

INC = -Icontrib/ -I../include
CFLAGS = -Wall -fexceptions -std=gnu++14
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = ./obj/Debug
DEP_DEBUG = 
OUT_DEBUG = ./bin/Debug/sayan_test

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = ./obj/Release
DEP_RELEASE = 
OUT_RELEASE = ./bin/Release/sayan_test

OBJ_DEBUG = $(OBJDIR_DEBUG)/main.o $(OBJDIR_DEBUG)/simple_test.o $(OBJDIR_DEBUG)/tests/algorithm/minmax.o $(OBJDIR_DEBUG)/tests/algorithm/modifying.o $(OBJDIR_DEBUG)/tests/algorithm/nonmodifying.o $(OBJDIR_DEBUG)/tests/algorithm/partitioning.o $(OBJDIR_DEBUG)/tests/algorithm/permutations.o $(OBJDIR_DEBUG)/tests/algorithm/set_operations.o $(OBJDIR_DEBUG)/tests/algorithm/sorting.o $(OBJDIR_DEBUG)/tests/cursor/concepts_check.o $(OBJDIR_DEBUG)/tests/cursor/inserters.o $(OBJDIR_DEBUG)/tests/cursor/istream.o $(OBJDIR_DEBUG)/tests/cursor/operations.o $(OBJDIR_DEBUG)/tests/cursor/ostream.o $(OBJDIR_DEBUG)/tests/cursor/reversed.o $(OBJDIR_DEBUG)/tests/numeric/numeric_algo.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/main.o $(OBJDIR_RELEASE)/simple_test.o $(OBJDIR_RELEASE)/tests/algorithm/minmax.o $(OBJDIR_RELEASE)/tests/algorithm/modifying.o $(OBJDIR_RELEASE)/tests/algorithm/nonmodifying.o $(OBJDIR_RELEASE)/tests/algorithm/partitioning.o $(OBJDIR_RELEASE)/tests/algorithm/permutations.o $(OBJDIR_RELEASE)/tests/algorithm/set_operations.o $(OBJDIR_RELEASE)/tests/algorithm/sorting.o $(OBJDIR_RELEASE)/tests/cursor/concepts_check.o $(OBJDIR_RELEASE)/tests/cursor/inserters.o $(OBJDIR_RELEASE)/tests/cursor/istream.o $(OBJDIR_RELEASE)/tests/cursor/operations.o $(OBJDIR_RELEASE)/tests/cursor/ostream.o $(OBJDIR_RELEASE)/tests/cursor/reversed.o $(OBJDIR_RELEASE)/tests/numeric/numeric_algo.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d ./bin/Debug || mkdir -p ./bin/Debug
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)
	test -d $(OBJDIR_DEBUG)/tests/algorithm || mkdir -p $(OBJDIR_DEBUG)/tests/algorithm
	test -d $(OBJDIR_DEBUG)/tests/cursor || mkdir -p $(OBJDIR_DEBUG)/tests/cursor
	test -d $(OBJDIR_DEBUG)/tests/numeric || mkdir -p $(OBJDIR_DEBUG)/tests/numeric

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/main.o: main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.cpp -o $(OBJDIR_DEBUG)/main.o

$(OBJDIR_DEBUG)/simple_test.o: simple_test.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c simple_test.cpp -o $(OBJDIR_DEBUG)/simple_test.o

$(OBJDIR_DEBUG)/tests/algorithm/minmax.o: tests/algorithm/minmax.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c tests/algorithm/minmax.cpp -o $(OBJDIR_DEBUG)/tests/algorithm/minmax.o

$(OBJDIR_DEBUG)/tests/algorithm/modifying.o: tests/algorithm/modifying.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c tests/algorithm/modifying.cpp -o $(OBJDIR_DEBUG)/tests/algorithm/modifying.o

$(OBJDIR_DEBUG)/tests/algorithm/nonmodifying.o: tests/algorithm/nonmodifying.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c tests/algorithm/nonmodifying.cpp -o $(OBJDIR_DEBUG)/tests/algorithm/nonmodifying.o

$(OBJDIR_DEBUG)/tests/algorithm/partitioning.o: tests/algorithm/partitioning.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c tests/algorithm/partitioning.cpp -o $(OBJDIR_DEBUG)/tests/algorithm/partitioning.o

$(OBJDIR_DEBUG)/tests/algorithm/permutations.o: tests/algorithm/permutations.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c tests/algorithm/permutations.cpp -o $(OBJDIR_DEBUG)/tests/algorithm/permutations.o

$(OBJDIR_DEBUG)/tests/algorithm/set_operations.o: tests/algorithm/set_operations.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c tests/algorithm/set_operations.cpp -o $(OBJDIR_DEBUG)/tests/algorithm/set_operations.o

$(OBJDIR_DEBUG)/tests/algorithm/sorting.o: tests/algorithm/sorting.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c tests/algorithm/sorting.cpp -o $(OBJDIR_DEBUG)/tests/algorithm/sorting.o

$(OBJDIR_DEBUG)/tests/cursor/concepts_check.o: tests/cursor/concepts_check.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c tests/cursor/concepts_check.cpp -o $(OBJDIR_DEBUG)/tests/cursor/concepts_check.o

$(OBJDIR_DEBUG)/tests/cursor/inserters.o: tests/cursor/inserters.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c tests/cursor/inserters.cpp -o $(OBJDIR_DEBUG)/tests/cursor/inserters.o

$(OBJDIR_DEBUG)/tests/cursor/istream.o: tests/cursor/istream.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c tests/cursor/istream.cpp -o $(OBJDIR_DEBUG)/tests/cursor/istream.o

$(OBJDIR_DEBUG)/tests/cursor/operations.o: tests/cursor/operations.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c tests/cursor/operations.cpp -o $(OBJDIR_DEBUG)/tests/cursor/operations.o

$(OBJDIR_DEBUG)/tests/cursor/ostream.o: tests/cursor/ostream.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c tests/cursor/ostream.cpp -o $(OBJDIR_DEBUG)/tests/cursor/ostream.o

$(OBJDIR_DEBUG)/tests/cursor/reversed.o: tests/cursor/reversed.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c tests/cursor/reversed.cpp -o $(OBJDIR_DEBUG)/tests/cursor/reversed.o

$(OBJDIR_DEBUG)/tests/numeric/numeric_algo.o: tests/numeric/numeric_algo.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c tests/numeric/numeric_algo.cpp -o $(OBJDIR_DEBUG)/tests/numeric/numeric_algo.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf ./bin/Debug
	rm -rf $(OBJDIR_DEBUG)
	rm -rf $(OBJDIR_DEBUG)/tests/algorithm
	rm -rf $(OBJDIR_DEBUG)/tests/cursor
	rm -rf $(OBJDIR_DEBUG)/tests/numeric

before_release: 
	test -d ./bin/Release || mkdir -p ./bin/Release
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)
	test -d $(OBJDIR_RELEASE)/tests/algorithm || mkdir -p $(OBJDIR_RELEASE)/tests/algorithm
	test -d $(OBJDIR_RELEASE)/tests/cursor || mkdir -p $(OBJDIR_RELEASE)/tests/cursor
	test -d $(OBJDIR_RELEASE)/tests/numeric || mkdir -p $(OBJDIR_RELEASE)/tests/numeric

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/main.o: main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.cpp -o $(OBJDIR_RELEASE)/main.o

$(OBJDIR_RELEASE)/simple_test.o: simple_test.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c simple_test.cpp -o $(OBJDIR_RELEASE)/simple_test.o

$(OBJDIR_RELEASE)/tests/algorithm/minmax.o: tests/algorithm/minmax.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c tests/algorithm/minmax.cpp -o $(OBJDIR_RELEASE)/tests/algorithm/minmax.o

$(OBJDIR_RELEASE)/tests/algorithm/modifying.o: tests/algorithm/modifying.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c tests/algorithm/modifying.cpp -o $(OBJDIR_RELEASE)/tests/algorithm/modifying.o

$(OBJDIR_RELEASE)/tests/algorithm/nonmodifying.o: tests/algorithm/nonmodifying.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c tests/algorithm/nonmodifying.cpp -o $(OBJDIR_RELEASE)/tests/algorithm/nonmodifying.o

$(OBJDIR_RELEASE)/tests/algorithm/partitioning.o: tests/algorithm/partitioning.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c tests/algorithm/partitioning.cpp -o $(OBJDIR_RELEASE)/tests/algorithm/partitioning.o

$(OBJDIR_RELEASE)/tests/algorithm/permutations.o: tests/algorithm/permutations.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c tests/algorithm/permutations.cpp -o $(OBJDIR_RELEASE)/tests/algorithm/permutations.o

$(OBJDIR_RELEASE)/tests/algorithm/set_operations.o: tests/algorithm/set_operations.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c tests/algorithm/set_operations.cpp -o $(OBJDIR_RELEASE)/tests/algorithm/set_operations.o

$(OBJDIR_RELEASE)/tests/algorithm/sorting.o: tests/algorithm/sorting.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c tests/algorithm/sorting.cpp -o $(OBJDIR_RELEASE)/tests/algorithm/sorting.o

$(OBJDIR_RELEASE)/tests/cursor/concepts_check.o: tests/cursor/concepts_check.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c tests/cursor/concepts_check.cpp -o $(OBJDIR_RELEASE)/tests/cursor/concepts_check.o

$(OBJDIR_RELEASE)/tests/cursor/inserters.o: tests/cursor/inserters.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c tests/cursor/inserters.cpp -o $(OBJDIR_RELEASE)/tests/cursor/inserters.o

$(OBJDIR_RELEASE)/tests/cursor/istream.o: tests/cursor/istream.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c tests/cursor/istream.cpp -o $(OBJDIR_RELEASE)/tests/cursor/istream.o

$(OBJDIR_RELEASE)/tests/cursor/operations.o: tests/cursor/operations.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c tests/cursor/operations.cpp -o $(OBJDIR_RELEASE)/tests/cursor/operations.o

$(OBJDIR_RELEASE)/tests/cursor/ostream.o: tests/cursor/ostream.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c tests/cursor/ostream.cpp -o $(OBJDIR_RELEASE)/tests/cursor/ostream.o

$(OBJDIR_RELEASE)/tests/cursor/reversed.o: tests/cursor/reversed.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c tests/cursor/reversed.cpp -o $(OBJDIR_RELEASE)/tests/cursor/reversed.o

$(OBJDIR_RELEASE)/tests/numeric/numeric_algo.o: tests/numeric/numeric_algo.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c tests/numeric/numeric_algo.cpp -o $(OBJDIR_RELEASE)/tests/numeric/numeric_algo.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf ./bin/Release
	rm -rf $(OBJDIR_RELEASE)
	rm -rf $(OBJDIR_RELEASE)/tests/algorithm
	rm -rf $(OBJDIR_RELEASE)/tests/cursor
	rm -rf $(OBJDIR_RELEASE)/tests/numeric

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

